#!/bin/sh
lb config noauto \
    --mode "debian" \
    --system "live" \
    --architectures "amd64" \
    --distribution "jessie" \
    --archive-areas "main contrib non-free" \
    --security "true" \
    --updates "true" \
    --backports "false" \
    --binary-filesystem "fat32" \
    --binary-images "iso-hybrid" \
    --apt-indices "true" \
    --apt-recommends "true" \
    --apt-secure "true" \
    --apt-source-archives "true" \
    --linux-package "linux-image" \
    --bootloader "syslinux" \
    --debian-installer "live" \
    --debian-installer-gui "true" \
    --iso-application "cmoi" \
    --iso-volume "cmoi" \
    --memtest "none" \
    --win32-loader "false" \
    --firmware-binary "true" \
    --firmware-chroot "true" \
    --clean \
    --debug \
    --verbose
"${@}"
